const products = [
  {
    _id: '1',
    name: 'iPhone 12 256GB',
    image: '/images/iphone12.png',
    description:
      'Is your phone lagging behind in terms of overall performance? Then, buy Apple iPhone 12 online, which comes with a fabulous display, amazing camera set up, and a powerful processor. Now, available in attractive colours',
    brand: 'Apple',
    category: 'Mobile Phones',
    price: 603.3,
    countInStock: 10,
    rating: 4.5,
    numReviews: 5,
  },
  {
    _id: '2',
    name: 'OnePlus 9 512GB',
    image: '/images/ON9.png',
    description:
      'Loaded with so many specifications, the OnePlus 9R features a brilliant camera combination of 48 MP (main camera), 16 MP (ultra-wide angle lens) 5 MP (macro lens), and 2 MP (monochrome lens). It takes awesome shots.',
    brand: 'One Plus',
    category: 'Mobile Phones',
    price: 361.98,
    countInStock: 7,
    rating: 4,
    numReviews: 2,
  },
  {
    _id: '3',
    name: 'iPad 64GB',
    image: '/images/ipad.png',
    description:
      'Widen your vision with the stunning and spectacular Apple iPad which flaunts an amazing display, brilliant camera and powerful processor. Available in vibrant classic colours it flaunts a sleek and thin design which is easy to hold and is crafted for perfect grip',
    brand: 'Apple',
    category: 'Tablets',
    price: 349.91,
    countInStock: 3,
    rating: 3.5,
    numReviews: 1,
  },
  {
    _id: '4',
    name: 'Apple Watch 6',
    image: '/images/applewatch.png',
    description:
      'Buy the Apple Watch Series 6 which is the GPS plus cellular model. It is of 40 mm case size (324 x 394 pixels, 759 sq mm display area). It comes with high and low heart rate notifications, irregular heart rhythm notification, and ECG app.',
    brand: 'Apple',
    category: 'Smart Watches',
    price: 422.31,
    countInStock: 6,
    rating: 3,
    numReviews: 10,
  },
  {
    _id: '5',
    name: 'Apple MacBook M1',
    image: '/images/macbook.png',
    description:
      'Use the Apple MacBook Air M1 Chip macOS Big Sur Laptop has set standards in computing thanks to its Apple M1 chip Processor. It has 7-Core CPU with 4 perform­ance cores and 4 efficiency cores, 7-core GPU, 16-core Neural Engine.',
    brand: 'Apple',
    category: 'Laptop',
    price: 1206.6,
    countInStock: 0,
    rating: 5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Airpods 3',
    image: '/images/airpods.png',
    description:
      'Do you like to enjoy music when it is delivered in great quality? Do you need perfect pods for your work? Then don’t wait to grab the Apple AirPods 3 In-Ear Truly Wireless Earbuds with Mic. With a contoured fit, force sensor controls, and a shorter stem, this is an all-new design',
    brand: 'Apple',
    category: 'Headphones',
    price: 217.19,
    countInStock: 4,
    rating: 4,
    numReviews: 3,
  },
  {
    _id: '7',
    name: 'OPPO A53 5G (8GB RAM, 128GB ROM)',
    image: '/images/oppo.png',
    description:
      'Get ready to witness the ultimate speed and performance when you buy Oppo A53s online, which comes loaded with various specifications. With 8GB RAM, you can install more applications and run them all together without disturbing the speed of the phone.',
    brand: 'Oppo',
    category: 'Mobile Phones',
    price: 216.19,
    countInStock: 4,
    rating: 3,
    numReviews: 3,
  },
  {
    _id: '8',
    name: 'Apple Earpods (In-Ear Headphones with Lightning Connector)',
    image: '/images/earpods.png',
    description:
      'Order Apple EarPods In-Ear Wired Earphone with Mic online, to get an awesome music companion. Unlike traditional, circular earbuds, the design of the EarPods is defined by the geometry of the ear. Which makes them more comfortable for more people than any other earbud-style headphones.',
    brand: 'Apple',
    category: 'Headphones',
    price: 18,
    countInStock: 10,
    rating: 3.5,
    numReviews: 5,
  },
  {
    _id: '9',
    name: 'Lenovo IdeaPad Slim 10th gen i5, Windows 11',
    image: '/images/lenovo.png',
    description:
      'Boost up your computing experience as the Lenovo IdeaPad Slim 3 10th Gen Core i5 Windows 11 Thin and Light Laptop features the latest advancements delivering efficient performance. The Lenovo IdeaPad Slim notebook is lightweight and portable. This machine, with its elegant look, will draw a lot of notice everywhere you go',
    brand: 'Lenovo',
    category: 'Laptops',
    price: 645.41,
    countInStock: 2,
    rating: 4,
    numReviews: 4,
  },
  {
    _id: '10',
    name: 'Redmi 10 Prime (6GB RAM)',
    image: '/images/redmi.png',
    description:
      'Get an awesome set of cameras and enhance your photography skills as you buy Xiaomi Redmi 10 Prime online. A stunning 50MP AI Quad Camera, supporting it we have an 8MP ultra-wide lens, a 2MP Macro with 2X Zoom for you to capture those close details that are missed out by the naked eye, and a 2MP depth sensor',
    brand: 'Xiaomi',
    category: 'Mobile Phones',
    price: 180.99,
    countInStock: 6,
    rating: 5,
    numReviews: 2,
  },
  {
    _id: '11',
    name: 'Anker Nebula Pocket Projector',
    image: '/images/anker.png',
    description:
      'Buy Anker Nebula Apollo Pocket Size Projector which helps you to browse your entertainment with pinpoint precision. Apollo’s transparent touch panel gives you the power to navigate menus and more with ease, directly from the device. Use the Anker Nebula Apollo Pocket Size Projector to connect HDMI and USB devices to Apollo to project your media on the big screen—you can even watch wirelessly with Airplay, Miracast, or Bluetooth',
    brand: 'Anker',
    category: 'Projectors',
    price: 446.44,
    countInStock: 3,
    rating: 4.5,
    numReviews: 3,
  },
  {
    _id: '12',
    name: 'Xiaomi Car Charger 18 Watts',
    image: '/images/charger.png',
    description:
      'Get the Xiaomi Mi Charger Pro 18 Watts/2.4 Amps 2 USB Ports Car Charging Adapter which is equipped with a premium design that delivers outstanding performance. It has an integrated and streamlined design, complemented by a metal housing made of high-quality brass to improve heat dissipation.',
    brand: 'Xiaomi',
    category: 'Chargers',
    price: 9.65,
    countInStock: 0,
    rating: 2.5,
    numReviews: 5,
  },
  {
    _id: '13',
    name: 'Noise Color Fit 3 Smart Watch',
    image: '/images/noise.png',
    description:
      'Monitoring health goals becomes easy when you buy Noise ColorFit Pro 3 Smart Watch (39.37mm) which can be the ideal fitness companion for you. It comes with a skin-friendly silicone strap that is comfortable to wear. Coming with Bluetooth 5.0 support, it is compatible with iOS 9 and Plus or Android 4.4 and Plus operating systems. ',
    brand: 'Noise',
    category: 'Smart Watches',
    price: 48.26,
    countInStock: 6,
    rating: 4.5,
    numReviews: 7,
  },
  {
    _id: '14',
    name: 'Sony True Wireless In-Ear Headphones',
    image: '/images/sony.png',
    description:
      'For those who live their life in music and find music in the tune of life, the Sony WF-XB700 In-Ear Truly Wireless Earbuds is a boon for them. If you want your music to be a constant companion to you then this is the ideal product for you with heighten your music experience by providing you with surround sound quality that you can never move on from.',
    brand: 'Sony',
    category: 'Headphones',
    price: 83.45,
    countInStock: 3,
    rating: 3.5,
    numReviews: 3,
  },
  {
    _id: '15',
    name: 'Canon 24.1MP DSLR Camera',
    image: '/images/canon.png',
    description:
      'Jazz up your photography skills with the Canon EOS 200D II, the lightest DSLR in the world. This compact DSLR is perfect for everyday photography as it easily glides inside the bag and weighs only a little more than a bottle of water. The petite camera packs in 24.1-megapixels APS-C CMOS sensor, DIGIC 8 processor and other stellar features that will make your clicking experience a comprehensive one',
    brand: 'Canon',
    category: 'Camera',
    price: 686.94,
    countInStock: 4,
    rating: 5,
    numReviews: 3,
  },
];

export default products;
